# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Guide to Academic Writing in Religious Studies 
#email: frederik.elwert@rub.de
description: > # this means to ignore newlines until "baseurl:"
  An introduction to academic skills in religious studies.
  Created at the Center for Religious Studies (CERES) of the Ruhr-Universit√§t Bochum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ceres-rub.github.io" # the base hostname & protocol for your site
twitter_username: CERES_RUB
github_username: CERES-RUB

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
